version: "3.9"

volumes:
  es_shipping_database_data:
    driver: local
  event_store_database_data:
    driver: local

services:
  es_shipping_database:
    image: postgres:14.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=es_shipping_db
      - POSTGRES_PASSWORD=es_shipping_pass
    volumes:
      - es_shipping_database_data:/var/lib/postgresql/es_shipping_data

  event_store_database:
    image: postgres:14.0
    ports:
      - 2113:5432
    environment:
      - POSTGRES_USER=event_store_db
      - POSTGRES_PASSWORD=event_store_pass
    volumes:
      - event_store_database_data:/var/lib/postgresql/event_store_data
